### ISSUE TITLE
New installation: crashes looking for quadpy.triangle

### ISSUE THREAD

**Issue by tkornack** [bfieldtools/bfieldtools#23]
Thanks for writing this software! 

I have an installation problem on macOS, running from the python 3.8 installed by the homebrew package manager. I attempted to install bfieldtools via pip, which worked except for mayavi, which needed to install from source to work with vtk 9. 

When I tried running some examples (try biplanar_coil_design.py), I found that some packages seemed to be missing. It seemed to require the packages mlab and trimesh, so I installed them. Now examples crash at 

```
  File "/usr/local/lib/python3.8/site-packages/bfieldtools/utils.py", line 90, in get_quad_points
    methods = [k for k in quadpy.triangle.__all__]
AttributeError: module 'quadpy' has no attribute 'triangle'
```

My quadpy seems to be right, but it indeed doesn't have anything like the attributes listed in `__all__`.

I also tested on a clean and up-to-date install of Ubuntu 20 with the default python3.8. I encountered the same problem with mayavi which was also fixed by installing it from source. I was not missing mlab and trimesh, but I found the same error in utils.py attempting `quadpy.triangle`.

**Comment by rzetter** [comment]
Hi, sorry for the installation troubles. Mayavi can be quite a pain to install. We've been looking at different alternatives with less cumbersome dependencies, but haven't settled for anything yet.

It's odd that trimesh wasn't installed together with bfieldtools as it's listed as a required dependency in the configuration files read by pip. Mlab is simply a part of the mayavi package. Regarding the quadpy issues, what version of quadpy do you have installed? The were some backwards-incompatible changes made at 0.13.0, bfieldtools requires a version => 0.13.0. This is also listed as a required dependency, did you specify the `--no-dependencies` option to pip when installing bfieldtools? Hopefully, running `pip install --upgrade quadpy` should fix things for you.

If not, my preferred workflow (will update the bfieldtools website to reflect this) is to use an [Anaconda](https://www.anaconda.com/) or [Miniconda](https://docs.conda.io/en/latest/miniconda.html) environment and install everything possible using `conda install`. This includes numpy, scipy, trimesh and most importantly, mayavi. Finally, one can then install bfieldtools using pip (bfieldtools isn't available through conda due to some dependencies not being available either).

I'm tagging @jiivana as well, since he has more up-to-date experience of getting mayavi/bfieldtools installed specifially on macOS than I do. :)

Hope this helps, or at least gets you started!

**Comment by tkornack** [comment]
Tried miniconda. I did `conda install mayavi` and then `pip install bfieldtools` which installed without error. Same error in quadpy. quadpy.triangle simply doesn't existing on any instance of quadpy 0.15.0 that I've seen. Is the attribute added during runtime?

**Comment by rzetter** [comment]
Sorry for the delayed response! It seems that quadpy has had another breaking API change (`quadpy.triangle` is now `quadpy.t2`). We'll update the code to work with newer versions of quadpy, if you're in a hurry then installing an older version should work: `pip install quadpy==0.13.2` (version proven to work).

**Comment by anttimc** [comment]
Hi!

My suggestion for now is to do the quadpy imports follows:
try:
    from quadpy import triangle
    from quadpy import line_segment
except ImportError:
    from quadpy import t2 as triangle
    from quadpy import c1 as line_segment

So we would support both the old <=0.14 and the new API. In future, when the API is stable, we can change this.

**Comment by tkornack** [comment]
Hi! Thanks for the fix! 

I just replaced with quadpy.t2 and it seems to work; I can't think of why you would need to support older quadpy.

**Comment by rzetter** [comment]
Great that things work! @anttimc also already to made a new release of bfieldtools (0.9.2) with the dual-API support in place. It's installable via pip!

**Comment by tkornack** [comment]
I don't see the commit. Is there another internal repository or branch that you're using?

**Comment by anttimc** [comment]
Sorry my bad. My previous push did not update the remote master branch, but now it should be ok.

**Comment by tkornack** [comment]
Kiitos paljon!
