### ISSUE TITLE
Replace mayavi with easier-to-install alternative

### ISSUE THREAD

**Issue by rzetter** [bfieldtools/bfieldtools#29]
Mayavi is a pest when it comes to installation issues. Here, let's suggest alternative 3D plotting solutions that would be preferable. @anttimc  had some suggestions earlier.

**Comment by anttimc** [comment]
Mayavi's mlab is very convenient for scripting. It is unfortunate that the installation is hard because of the dependencies. Conda has worked for me but I haven't tried installing it for a while.

Matplotlib has some [3D plotting functionalities](https://jakevdp.github.io/PythonDataScienceHandbook/04.12-three-dimensional-plotting.html)  but the options might be a little too limited for our purposes.

[Polyscope](https://polyscope.run/py/) is a 3D viewer written in  C++ and binded with pybind11. I tried installing it and played around with it for a while. It had a very intuitive interactive GUI. However, when I tried to plot another scene in the same Ipython session, the scene did not open. Maybe there was process hanging that I should have manually shut down? We should be more familiar with how it works before condidering it an alternative for mayavi.

**Comment by anttimc** [comment]
Plotly seems to have everything we need for our current plots. The interative plots should always be saved in a html file and viewed in a browser since the rendering is based on JavaScript, but I don't think it's a bad thing. Once saved, it's easy to share the plots for example in a presentation or on our website. It might also be possible to save everything to svg including 3D plots, which would be a big bonus compared to Mayavi.

**Comment by rzetter** [comment]
Another alternative that was pointed out to me is [pyvista](https://docs.pyvista.org/index.html), which is also based on vtk but apparently is a 'cleaner implementation'. It seems to have quite a bit of impressive functionality (comparable to mayavi in scope). MNE-python recently switched over from mayavi to pyvista, here's a related discussion: https://github.com/pyvista/pyvista/issues/146.

I'll create a separate branch for testing pyvista. Plotly is also somewhat promising, but I'm a bit hesitant with the whole browser-based aspect.

**Comment by anttimc** [comment]
Pyvista has similar features as mayavi, but instead of using tvtk and e.g. mlab.pipeline to get to use the power of vtk, pyvista exposes the underlying vtk properties with a more transparent interface. What is missing is the interactive GUI with a script recorder which I really liked in some situations when tuning the plots. However, if the installation/dependency handling is easier, my vote goes for pyvista.

**Comment by rzetter** [comment]
Having played around a bit more with pyvista, I agree regarding the interactive GUI + script recorder, it is very handy when "prototyping" plots. For our own use (when mayavi is working), switching to pyvista wouldn't really bring any advantages (and I would miss the GUI part), so I'm not in such a hurry in moving away from mayavi even though that's what we should do long-term. On paper, the dependency handling should be similar nowadays between the two, but I still keep running into issues with mayavi (e.g. currently when migrating to Github Actions).

PS. One handy quality-of-life thing I discovered with Pyvista is that it can natively handle trimesh objects when plotting.

**Comment by rzetter** [comment]
Pyvista has matured over the past years, and now MNE-Python has also abandoned mayavi and gone over to pyvista. I have now pushed a commit to master replaced mayavi with pyvista. Examples are still untouched though.

**Comment by rzetter** [comment]
New release based on Pyvista, 0.11.3.
