### ISSUE TITLE
Figure option in plot functions

### ISSUE THREAD

**Issue by anttimc** [bfieldtools/bfieldtools#30]
It seems to me that the `figure` parameter in the plotting functions of viz is a bit misleading. By default `figure=None`, and the functions create a new mlab.figure, which create a new mayavi scene. However, if you pass a handle to any figure (scene) the functions do nothing with the handle. You can pass basically any other object as `figure`  and by default mayavi plots to the scene you have already open.

Two alternative suggestions:
1) Change `figure `to boolean `new_figure`  and change the default to `True`. This would have the same behaviour as the plotting functions currently have. 

2) Pass the desired scene into the function as `scene`. In that case, the object should be handled in every function correctly so that the function really plots in the given scene. The functions should also check if the given object is a proper a scene.

In both options, in my opinion, it would be better to not create a new figure/scene by default. Usually when scripting I want to see two things in the same scene (e.g., a mesh and a quiver plot). Only in very few cases, I want to create a new figure for every plotted object in the same script.

**Comment by rzetter** [comment]
It seems like the functions in viz aren't using the figure parameter (if passed). Funnily enough, this has mostly worked since they are then by default plotted to the previously active figure. This should definitely be fixed. Regarding type checks, it's a good idea in general but I don't think it's necessary for our audience and in this case (also considering the docstring etc). 

I don't know why you would prefer passing scenes rather than figures. The "mlab.plotfoo" functions take figures as parameters, see e.g. https://docs.enthought.com/mayavi/mayavi/auto/mlab_helper_functions.html#quiver3d


Regarding the default setting, I prefer getting separate plots by default. In one plot, I might be showing the geometry in one plot, in another the stream function, and in the next the discretized current loops. For me, plotting many things in the same figure is the "conscious choice". However, the default behavior of matplotlib and mayavi is to plot in the same window, so I guess that's the way to do it. This would mean the behavior in suggestion 1, although it bothers me that we would then be unable to specify which figure to plot to other than by activating the right figure before calling the plot function.
