### ISSUE TITLE
Bug in mesh_magnetics.py

### ISSUE THREAD

**Issue by femisan** [bfieldtools/bfieldtools#31]
At line 386 of mesh_magnetics.py,  this function is supposed to return an array with dim (Np,3, Nvertices). However, it returns (3, Np, Nvertices).
I think it should be 
return np.swapaxes(Av * coeff,0,1)

**Comment by rzetter** [comment]
Thanks for noticing this! Indeed, vector_potential_coupling returns an array with shape (3, Npoints, Nvertices) instead of (Npoints, 3, Nvertices) as stated in the docstring. I've changed the return shape to conform to the docstring (commit a419c2a793ab7eff6b52e3cd841a424126dff18d) and made a new bugfix release (0.9.5) which should be available via pip shortly. 

This was a good catch since the shape also caused issue with the caching functionality of MeshConductor.A_coupling(points).

**Comment by rzetter** [comment]
The new pip release is not yet available due to problems with our CI system, see #32.

**Comment by rzetter** [comment]
Travis id working for now, so the new release is now in pip!
