### ISSUE TITLE
How do you calculate the mutual inductance of any given wire not determind by bfieldtools?

### ISSUE THREAD

**Issue by 3masa25smile** [bfieldtools/bfieldtools#50]
I would like to know how to calculate mutual inductance by bfieldtools.

I know how to calculate the mutual inductance of wire determinded by bfieldtools 
https://github.com/bfieldtools/bfieldtools/blob/e6997f1b22ea0bac64179b965b99d172041a1775/bfieldtools/line_magnetics.py#L168

Here, I would like to know how to calculate the mutual inductance of wire designted by myself.  

For example, I would like to know the mutual inductance of simple two circulars coil by bfieldtools. 
https://github.com/bfieldtools/bfieldtools/blob/master/examples/misc_examples/helmholtz_coil.py

I saved points data. 
np.savetxt('c1_points.csv', c1_points, delimiter=',')
np.savetxt('c2_points.csv', c2_points, delimiter=',')

However, I have no good idea to use function "mutual_inductance(path1, path2, Nquad=2, radius=1e-3) ".

Please give me advice!

**Comment by anttimc** [comment]
Hi,

I have not looked into the code for a while, but it seems to me that mutual_inductance is a helper function used by the `LineConductor` class at least (interface for many line conductor features). `LineConductor` inherits `Path3D` of the `trimesh` module. The reason why we've chosen to use `Path3D` instead of bare arrays is that it has a structure to support multiple current loops.

If you read the docstring of mutual_inductance, you see that `path1` and `path2` are expected to be `Path3D` objects. It's possible that you construct `Path3D` objects from `c1_points` and `c2_points` but I think the following would be easier
```
c1 = LineConductor(loops=[c1_points])
c2 = LineConductor(loops=[c2_points])
mutual_inductance_between_c1_and_c2 = c1.line_mutual_inductance(c2)
```
I have not tested this code, so I'm not 100% sure if it works. But hopefully you'll get forward with this.

**Comment by 3masa25smile** [comment]
> Hi,
> 
> I have not looked into the code for a while, but it seems to me that mutual_inductance is a helper function used by the `LineConductor` class at least (interface for many line conductor features). `LineConductor` inherits `Path3D` of the `trimesh` module. The reason why we've chosen to use `Path3D` instead of bare arrays is that it has a structure to support multiple current loops.
> 
> If you read the docstring of mutual_inductance, you see that `path1` and `path2` are expected to be `Path3D` objects. It's possible that you construct `Path3D` objects from `c1_points` and `c2_points` but I think the following would be easier
> 
> ```
> c1 = LineConductor(loops=[c1_points])
> c2 = LineConductor(loops=[c2_points])
> mutual_inductance_between_c1_and_c2 = c1.line_mutual_inductance(c2)
> ```
> 
> I have not tested this code, so I'm not 100% sure if it works. But hopefully you'll get forward with this.

Thank you very much! Great help!!
