### ISSUE TITLE
pyqt version pinning breaks installation on apple silicon

### ISSUE THREAD

**Issue by tkornack** [bfieldtools/bfieldtools#58]
Why is pyqt pinned to less than version 5.15? 

It works fine for me on linux and macOS to unpin the version.

**Comment by rzetter** [comment]
Hi Tom! The PyQt version pinning was required by previous version of mayavi, the 3D visualization library used in bfieldtools. Mayavi itself seems to be pretty poorly maintained for now, and it has always been a pain to install on different platforms. My intention is to replace mayavi with pyvista as soon as I have time. 

As you already noticed, the version pinning can be removed, PyQt has no influence on the core bfieldtools functionality. Good to hear that the package otherwise works on Apple Silicon/ARM, that's not something I've tested.

**Comment by rzetter** [comment]
I found some time to migrate the 3D visualization functions to Pyvista, a new release (0.11.3) should now be available via PyPI. With this, no explicit PyQt dependency is needed any longer.  On Windows x64 the new release installs without issues to a blank conda environment simply via "pip install bfieldtools". Hopefully the same is the case for Apple ARM.

**Comment by tkornack** [comment]
Thanks!
